EMOTICON_POSES = [
    "smiling brightly",
    "crying with big tears",
    "angry with steam from nose",
    "laughing with eyes closed",
    "sleeping with bubble from nose",
    "surprised with wide eyes",
    "shouting loudly",
    "sweating nervously",
    "blushing and smiling",
    "pouting with arms crossed",
    "making a heart with hands",
    "sending a flying kiss",
    "winking playfully",
    "thumbs up",
    "facepalming",
    "looking bored",
    "wearing sunglasses coolly",
    "making a peace sign",
    "raising eyebrows in disbelief",
    "eating ramen happily",
    "drinking coffee calmly",
    "hiding behind hands shyly",
    "jumping with joy",
    "hugging a teddy bear",
    "doing a dance move",
    "teary-eyed while smiling",
    "angry with fists clenched",
    "snoring loudly",
    "giving a side-eye glance",
    "blowing bubble gum",
    "wrapped in a blanket like a burrito",
    "celebrating with confetti",
    "holding a sign that says 'OK'",
    "holding a sign that says 'NO'",
    "acting shocked with hands on cheeks",
    "duck face selfie pose",
    "holding a bouquet of flowers",
    "doing a double thumbs up",
    "blowing a party horn",
    "wearing a birthday hat",
    "doing a finger heart",
    "wearing cat ears playfully",
    "whistling innocently",
    "brows furrowed in focus",
    "smirking mischievously",
    "peeking from behind a wall",
    "bowing politely",
    "panicking with hands up",
    "sleeping while sitting",
    "getting squished in a hug",
    "looking proud with arms crossed",
    "waving excitedly",
    "sneezing",
    "shivering from cold",
    "panting tiredly",
    "licking lips hungrily",
    "feeling dizzy with spiraled eyes",
    "raising one eyebrow",
    "saluting like a soldier",
    "doing yoga",
    "wearing a crown confidently",
    "wearing a hoodie and hiding",
    "looking heartbroken",
    "blowing kisses with both hands",
    "wearing glasses and reading",
    "posing like a K-pop idol",
    "giving a sassy hand wave",
    "pretending to cry",
    "laughing like a villain",
    "floating with angel wings",
    "hiding under a table",
    "knocked out with stars around head",
    "looking smug with raised chin",
    "crying in the rain",
    "playing a tiny violin",
    "with a question mark above head",
    "with an idea lightbulb above head",
    "throwing money in the air",
    "wearing a sleep mask",
    "typing frantically",
    "eating popcorn",
    "with hands over mouth in shock",
    "doing a silly dance",
    "sitting with legs crossed and sipping tea",
    "dancing in the rain",
    "hugging knees while sulking",
    "charging up with sparks",
    "bouncing on a trampoline",
    "with fire in the eyes",
    "with hearts for eyes",
    "grinning mischievously",
    "wearing a frog hat",
    "wearing a bunny costume",
    "playing dead dramatically",
    "slamming a table",
    "staring blankly into space",
    "holding a pillow and yawning",
    "wearing a bandage and looking sick",
    "juggling",
    "sitting on a cloud",
    "pretending to be invisible",
    "daydreaming with hearts around",
    "poking someone cutely",
    "with a fish in mouth",
    "cry-laughing with tears streaming",
    "watching TV with snacks",
    "spinning in a chair",
    "riding a bike with joy",
    "hiding behind a plush toy",
    "floating on a pool ring",
    "pretending to fly like Superman",
    "posing like a ninja",
    "holding a fake mustache",
    "wearing traditional clothes and smiling",
    "making a puppy face",
    "playing with a balloon",
    "smashing a keyboard",
    "knitting calmly",
    "in a panic with swirling arms",
    "with a hoodie zipped all the way up",
    "doing finger guns",
    "high-fiving",
    "receiving a gift box",
    "throwing confetti",
    "biting lip nervously",
    "stuck in a tight space",
    "floating in zero gravity",
    "wearing headphones and vibing",
    "balancing on one foot",
    "pretending to be asleep",
    "shocked by lightning",
    "watching fireworks",
    "blown away by wind",
    "with a magnet attracting hearts",
    "covered in sticky notes",
    "wearing too-big clothes",
    "mimicking a cat paw pose",
    "posing like a celebrity on the red carpet",
    "posing like a fashion model",
    "doing a karate move",
    "posing as a wizard",
    "hiding behind a giant coffee mug",
    "pretending to be an alien",
    "celebrating payday",
    "eating noodles with messy face",
    "looking confused with scribbles above head",
    "blinking rapidly in disbelief",
    "spitting out water in shock",
    "pulling cheeks playfully",
    "punching the air victoriously",
    "flipping a pancake",
    "jump-scare face",
    "floating with love hearts",
    "smelling a flower"
]

DEFAULT_STYLES = {
    "Pixar Style": "a Pixar-style cute 3D cartoon character",
    "Webtoon Style": "a Webtoon-style digital illustration of a character with expressive facial features",
    "Watercolor Style": "a watercolor portrait illustration in soft tones and brush strokes",
    "Black & White Sketch": "a monochrome pencil sketch portrait with detailed shading",
    "Anime Style": "an anime-style headshot with large expressive eyes, cel-shaded",
    "Minimal Character": "a flat, minimalistic character icon in pastel tones, Korean emoticon style"
}
IMAGE_GENERATE_PROMPT = """
Generate a 3x3 grid of square KakaoTalk-style cartoon emoticons based on the person's appearance in the reference photo. 
Each cell should depict a different action-based pose such as: {pose_text}.
The character should be {style_prompt}. Use a transparent background, no text, no borders, and no background objects.
Center each character in a 256x256 square. The output image must be 768x768 pixels. 
Background should be transparent, and the characters should be in a cute, cartoonish style suitable for KakaoTalk emoticons.
""".strip()